// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type AssignedTestGroup = {
    label: string;
    greeting?: string | null;
    allowPreviousPhase: boolean;
    allowPreviousQuestion: boolean;
    allowSkipQuestion: boolean;
    phases: Array<AssignedTestPhase>;
};

export type AssignedTestOption = {
    id: number;
    text?: string | null;
    image?: Image | null;
};

export type AssignedTestPhase = {
    questions: Array<AssignedTestQuestion>;
};

export type AssignedTestQuestion = {
    id: number;
    text?: string | null;
    image?: Image | null;
    options: Array<AssignedTestOption>;
};

export type Image = {
    url: string;
    alt: string;
};

export type UserTestAttempt = {
    completedPreTestForm: boolean;
    completedTest: boolean;
    completedPostTestForm: boolean;
    testAnswers: Array<UserTestAttemptAnswer>;
    assignedGroup: AssignedTestGroup;
};

export type UserTestAttemptAnswer = {
    questionId: number;
    optionId: number;
};

export type NewFormAnswer = {
    questionId: number;
    optionId?: number;
    value?: number;
    answer?: string;
};

export type NewFormAnswers = {
    answers: Array<NewFormAnswer>;
};

export type NewQuestionEventLog = {
    questionId: number;
    timestamp: number;
    duration: number;
};

export type NewOptionEventLog = {
    optionId: number;
    type: 'deselect' | 'select' | 'hover';
    timestamp: number;
};

export type NewUser = {
    username: string;
    name?: string;
    email?: string;
    age?: number;
    password: string;
};

export type Token = {
    token: string;
};

export type Credentials = {
    username: string;
    password: string;
};

export type User = {
    id: number;
    username: string;
    anonymous: boolean;
    name?: string;
    email?: string;
    age?: number;
};

export type ConfigUpdate = {
    title: string;
    subtitle: string;
    description: string;
    anonymous: boolean;
    usernamePattern?: PatternUpdate;
    informedConsent: string;
    informationCards?: Array<InformationCardUpdate>;
    faq?: Array<FrequentlyAskedQuestionUpdate>;
    preTestForm?: FormUpdate;
    postTestForm?: FormUpdate;
    groups: Array<TestGroupUpdate>;
    translations: {
        [key: string]: string;
    };
};

export type FormOptionUpdate = {
    id?: number;
    text?: string;
};

export type FormQuestionUpdate = unknown;

export type FormUpdate = {
    id?: number;
    title?: string;
    questions: Array<SelectMultipleUpdate | SelectOneUpdate | SliderUpdate | TextLongUpdate | TextShortUpdate>;
};

export type FrequentlyAskedQuestionUpdate = {
    id?: number;
    question: string;
    answer: string;
};

export type InformationCardUpdate = {
    id?: number;
    title: string;
    description: string;
    color: number;
};

export type PatternUpdate = {
    id?: number;
    name: string;
    regex: string;
};

export type SelectMultipleUpdate = FormQuestionUpdate & {
    id?: number;
    category: string;
    text?: string;
    type: 'select-multiple';
    min: number;
    max: number;
    other: boolean;
    options: Array<FormOptionUpdate>;
};

export type SelectOneUpdate = FormQuestionUpdate & {
    id?: number;
    category: string;
    text?: string;
    type: 'select-one';
    other: boolean;
    options: Array<FormOptionUpdate>;
};

export type SliderLabelUpdate = {
    id?: number;
    number: number;
    label: string;
};

export type SliderUpdate = FormQuestionUpdate & {
    id?: number;
    category: string;
    text?: string;
    type: 'slider';
    min: number;
    max: number;
    step: number;
    labels: Array<SliderLabelUpdate>;
};

export type TestGroupUpdate = {
    id?: number;
    probability: number;
    label: string;
    greeting?: string;
    allowPreviousPhase: boolean;
    allowPreviousQuestion: boolean;
    allowSkipQuestion: boolean;
    randomizePhases: boolean;
    phases: Array<TestPhaseUpdate>;
};

export type TestOptionUpdate = {
    id?: number;
    text?: string;
    correct: boolean;
};

export type TestPhaseUpdate = {
    id?: number;
    randomizeQuestions: boolean;
    questions: Array<TestQuestionUpdate>;
};

export type TestQuestionUpdate = {
    id?: number;
    text?: string;
    randomizeOptions: boolean;
    options: Array<TestOptionUpdate>;
};

export type TextLongUpdate = FormQuestionUpdate & {
    id?: number;
    category: string;
    text?: string;
    type: 'text-long';
    placeholder: string;
    minLength: number;
    maxLength: number;
};

export type TextShortUpdate = FormQuestionUpdate & {
    id?: number;
    category: string;
    text?: string;
    type: 'text-short';
    placeholder: string;
    minLength: number;
    maxLength: number;
};

export type UserSummary = {
    id: number;
    name: string;
    email: string;
    age: number;
    timestamp: number;
    timeTaken: number;
    correctQuestions: number;
    questionsAnswered: number;
    accuracy: number;
};

export type UsersSummary = {
    averageAccuracy: number;
    averageTimeTaken: number;
    totalQuestionsAnswered: number;
    users: Array<UserSummary>;
};

export type QuestionTimestamp = {
    start: number;
    end: number;
};

export type TestQuestionResult = {
    questionId: number;
    timestamps: Array<QuestionTimestamp>;
    correct: boolean;
    skipped: boolean;
    totalOptionChanges: number;
    totalOptionHovers: number;
};

/**
 * Resultados de test de un usuario
 */
export type TestResultByUser = {
    /**
     * Información del usuario, incluyendo el ID de grupo de test
     */
    user?: UserBasicInfo;
    /**
     * Resultados por pregunta
     */
    questions?: Array<TestQuestionResult>;
};

/**
 * Datos básicos de un usuario
 */
export type UserBasicInfo = {
    /**
     * ID del usuario
     */
    id?: number;
    /**
     * Nombre del usuario
     */
    name?: string;
    /**
     * Email del usuario
     */
    email?: string;
    /**
     * Edad del usuario
     */
    age?: number;
};

/**
 * Respuesta de un usuario a una pregunta del formulario.
 */
export type FormAnswer = {
    /**
     * ID de la pregunta
     */
    questionId: number;
    /**
     * Texto de la pregunta
     */
    questionText: string;
    /**
     * ID de la opcion seleccionada (si es pertinente))
     */
    optionId?: number;
    /**
     * Texto de la opcion seleccionada (si es pertinente)
     */
    optionText?: string;
    /**
     * Valor numerico de la respuesta (si es pertinente)
     */
    value?: number;
    /**
     * Respuesta en texto libre (si es pertinente)
     */
    answer?: string;
};

/**
 * Contiene las respuestas a un formulario especifico.
 */
export type FormAnswers = {
    /**
     * ID del formulario
     */
    formId: number;
    /**
     * Título del formulario
     */
    formTitle: string;
    /**
     * Respuestas a preguntas del formulario
     */
    answers: Array<FormAnswer>;
};

/**
 * Respuestas de los resultados de los formularios (pre-test y post-test) de un usuario
 */
export type FormAnswersByUser = {
    /**
     * Información del usuario, incluyendo el ID de grupo de test
     */
    user?: UserBasicInfo;
    /**
     * Resultados de formularios pre-test
     */
    pre?: Array<FormAnswers>;
    /**
     * Resultados de formularios post-test
     */
    post?: Array<FormAnswers>;
};

/**
 * Resultados completos (formularios y tests) de un usuario, con info de usuario unica
 */
export type ResultsByUser = {
    /**
     * Datos del usuario
     */
    user?: UserBasicInfo;
    /**
     * Resultados de formularios
     */
    forms?: UserFormsResult;
    /**
     * Resultados de test
     */
    tests?: UserTestsResult;
};

export type UserFormsResult = {
    pre?: Array<FormAnswers>;
    post?: Array<FormAnswers>;
};

export type UserTestsResult = {
    questions?: Array<TestQuestionResult>;
};

export type OptionEventLog = {
    optionId: number;
    type: 'deselect' | 'select' | 'hover';
    timestamp: number;
};

export type OptionSelectionEvent = {
    optionId: number;
    timestamp: number;
};

export type QuestionEventLogWithUserId = {
    userId: number;
    questionId: number;
    timestamps: Array<QuestionTimestamp>;
    correct: boolean;
    skipped: boolean;
    totalOptionChanges: number;
    totalOptionHovers: number;
    optionSelections: Array<OptionSelectionEvent>;
    events: Array<OptionEventLog>;
};

export type QuestionEventLog = {
    questionId: number;
    timestamps: Array<QuestionTimestamp>;
    correct: boolean;
    skipped: boolean;
    totalOptionChanges: number;
    totalOptionHovers: number;
    optionSelections: Array<OptionSelectionEvent>;
    events: Array<OptionEventLog>;
};

export type ConfigPreview = {
    version: number;
    icon?: Image | null;
    title: string;
    subtitle?: string | null;
    description: string;
    active: boolean;
    canDelete: boolean;
};

export type Form = {
    id: number;
    questions: Array<SelectMultiple | SelectOne | Slider | TextLong | TextShort>;
};

export type FormOption = {
    id: number;
    text?: string | null;
    image?: Image | null;
};

export type FormQuestion = unknown;

export type FrequentlyAskedQuestion = {
    id: number;
    question: string;
    answer: string;
};

export type FullConfig = {
    version: number;
    icon?: Image | null;
    title: string;
    subtitle?: string | null;
    description: string;
    anonymous: boolean;
    usernamePattern?: Pattern;
    informationCards: Array<InformationCard>;
    informedConsent: string;
    frequentlyAskedQuestion: Array<FrequentlyAskedQuestion>;
    preTestForm?: Form | null;
    postTestForm?: Form | null;
    groups: Array<TestGroup>;
    translations: Array<Translation>;
};

export type InformationCard = {
    id: number;
    title: string;
    description: string;
    color?: number | null;
    icon?: Image | null;
};

export type Pattern = {
    id: number;
    name: string;
    regex: string;
};

export type SelectMultiple = FormQuestion & {
    id: number;
    category: string;
    text?: string | null;
    image?: Image | null;
    type: 'select-multiple';
    options: Array<FormOption>;
    min: number;
    max: number;
    other: boolean;
};

export type SelectOne = FormQuestion & {
    id: number;
    category: string;
    text?: string | null;
    image?: Image | null;
    type: 'select-one';
    options: Array<FormOption>;
    other: boolean;
};

export type Slider = FormQuestion & {
    id: number;
    category: string;
    text?: string | null;
    image?: Image | null;
    type: 'slider';
    min: number;
    max: number;
    step: number;
    labels: Array<SliderLabel>;
};

export type SliderLabel = {
    id: number;
    number: number;
    label: string;
};

export type TestGroup = {
    id: number;
    probability: number;
    label: string;
    greeting?: string | null;
    allowPreviousPhase: boolean;
    allowPreviousQuestion: boolean;
    allowSkipQuestion: boolean;
    randomizePhases: boolean;
    phases: Array<TestPhase>;
};

export type TestOption = {
    id: number;
    text?: string | null;
    image?: Image | null;
    correct: boolean;
};

export type TestPhase = {
    id: number;
    randomizeQuestions: boolean;
    questions: Array<TestQuestion>;
};

export type TestQuestion = {
    id: number;
    text?: string | null;
    image?: Image | null;
    randomizeOptions: boolean;
    options: Array<TestOption>;
};

export type TextLong = FormQuestion & {
    id: number;
    category: string;
    text?: string | null;
    image?: Image | null;
    type: 'text-long';
    placeholder: string;
    minLength: number;
    maxLength: number;
};

export type TextShort = FormQuestion & {
    id: number;
    category: string;
    text?: string | null;
    image?: Image | null;
    type: 'text-short';
    placeholder: string;
    minLength: number;
    maxLength: number;
};

export type Translation = {
    key: string;
    value?: string | null;
    description: string;
    arguments: Array<string>;
};

export type TrimmedConfig = {
    icon?: Image | null;
    title: string;
    subtitle?: string | null;
    description: string;
    anonymous: boolean;
    usernamePattern?: Pattern;
    informationCards: Array<InformationCard>;
    informedConsent: string;
    frequentlyAskedQuestion: Array<FrequentlyAskedQuestion>;
    preTestForm?: Form | null;
    postTestForm?: Form | null;
    translations: {
        [key: string]: string;
    };
};

export type ApiHttpError = {
    code: number;
    message: string;
    errors?: Array<FieldError>;
};

export type FieldError = {
    field: string;
    message: string;
};

export type EndTestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/test/end';
};

export type EndTestErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
};

export type EndTestError = EndTestErrors[keyof EndTestErrors];

export type EndTestResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DiscardTestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/test/discard';
};

export type DiscardTestErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
};

export type DiscardTestError = DiscardTestErrors[keyof DiscardTestErrors];

export type DiscardTestResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ContinueTestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/test/continue';
};

export type ContinueTestErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
};

export type ContinueTestError = ContinueTestErrors[keyof ContinueTestErrors];

export type ContinueTestResponses = {
    /**
     * OK
     */
    200: UserTestAttempt;
};

export type ContinueTestResponse = ContinueTestResponses[keyof ContinueTestResponses];

export type BeginTestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/test/begin';
};

export type BeginTestErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
};

export type BeginTestError = BeginTestErrors[keyof BeginTestErrors];

export type BeginTestResponses = {
    /**
     * OK
     */
    200: UserTestAttempt;
};

export type BeginTestResponse = BeginTestResponses[keyof BeginTestResponses];

export type SubmitFormAnswersData = {
    body: NewFormAnswers;
    path: {
        formType: 'pre' | 'post';
    };
    query?: never;
    url: '/api/forms/{formType}/answers';
};

export type SubmitFormAnswersErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
    /**
     * Validation error
     */
    422: ApiHttpError;
};

export type SubmitFormAnswersError = SubmitFormAnswersErrors[keyof SubmitFormAnswersErrors];

export type SubmitFormAnswersResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type SaveQuestionEventLogData = {
    body: NewQuestionEventLog;
    path?: never;
    query?: never;
    url: '/api/event-logs/question';
};

export type SaveQuestionEventLogErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
    /**
     * Validation error
     */
    422: ApiHttpError;
};

export type SaveQuestionEventLogError = SaveQuestionEventLogErrors[keyof SaveQuestionEventLogErrors];

export type SaveQuestionEventLogResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type SaveOptionEventLogData = {
    body: NewOptionEventLog;
    path?: never;
    query?: never;
    url: '/api/event-logs/option';
};

export type SaveOptionEventLogErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
    /**
     * Validation error
     */
    422: ApiHttpError;
};

export type SaveOptionEventLogError = SaveOptionEventLogErrors[keyof SaveOptionEventLogErrors];

export type SaveOptionEventLogResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type SetConfigAsActiveData = {
    body?: never;
    path: {
        version: number;
    };
    query?: never;
    url: '/api/configs/{version}/activate';
};

export type SetConfigAsActiveErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
};

export type SetConfigAsActiveError = SetConfigAsActiveErrors[keyof SetConfigAsActiveErrors];

export type SetConfigAsActiveResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RegisterData = {
    body: NewUser;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterErrors = {
    /**
     * Validation error
     */
    422: ApiHttpError;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * OK
     */
    200: Token;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LoginData = {
    body: Credentials;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * Validation error
     */
    422: ApiHttpError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * OK
     */
    200: Token;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type GetCurrentAdminData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/me';
};

export type GetCurrentAdminErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
};

export type GetCurrentAdminError = GetCurrentAdminErrors[keyof GetCurrentAdminErrors];

export type GetCurrentAdminResponses = {
    /**
     * OK
     */
    200: User;
};

export type GetCurrentAdminResponse = GetCurrentAdminResponses[keyof GetCurrentAdminResponses];

export type GetActiveConfigAsUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/configs/active';
};

export type GetActiveConfigAsUserResponses = {
    /**
     * OK
     */
    200: TrimmedConfig;
};

export type GetActiveConfigAsUserResponse = GetActiveConfigAsUserResponses[keyof GetActiveConfigAsUserResponses];

export type UpdateActiveConfigData = {
    body: {
        /**
         * New application icon
         */
        icon?: Blob | File;
        /**
         * Every image used in the information cards
         */
        informationCardImages?: Array<Blob | File>;
        /**
         * Every image used in the pre-test form
         */
        preTestFormImages?: Array<Blob | File>;
        /**
         * Every image used in the post-test form
         */
        postTestFormImages?: Array<Blob | File>;
        /**
         * Every image used in the test groups
         */
        groupImages?: Array<Blob | File>;
        /**
         * Configuration update
         */
        payload: ConfigUpdate;
    };
    path?: never;
    query?: never;
    url: '/api/configs/active';
};

export type UpdateActiveConfigErrors = {
    /**
     * Validation error
     */
    422: ApiHttpError;
};

export type UpdateActiveConfigError = UpdateActiveConfigErrors[keyof UpdateActiveConfigErrors];

export type UpdateActiveConfigResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetAllUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type GetAllUsersErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
};

export type GetAllUsersError = GetAllUsersErrors[keyof GetAllUsersErrors];

export type GetAllUsersResponses = {
    /**
     * OK
     */
    200: Array<User>;
};

export type GetAllUsersResponse = GetAllUsersResponses[keyof GetAllUsersResponses];

export type GetUserData = {
    body?: never;
    path: {
        username: string;
    };
    query?: never;
    url: '/api/users/{username}';
};

export type GetUserErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * OK
     */
    200: User;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type GetCurrentUserErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
};

export type GetCurrentUserError = GetCurrentUserErrors[keyof GetCurrentUserErrors];

export type GetCurrentUserResponses = {
    /**
     * OK
     */
    200: User;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type GetAllUserSummariesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/summary';
};

export type GetAllUserSummariesErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
};

export type GetAllUserSummariesError = GetAllUserSummariesErrors[keyof GetAllUserSummariesErrors];

export type GetAllUserSummariesResponses = {
    /**
     * OK
     */
    200: UsersSummary;
};

export type GetAllUserSummariesResponse = GetAllUserSummariesResponses[keyof GetAllUserSummariesResponses];

export type GetUserSummaryByIdData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/api/summary/{userId}';
};

export type GetUserSummaryByIdErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
};

export type GetUserSummaryByIdError = GetUserSummaryByIdErrors[keyof GetUserSummaryByIdErrors];

export type GetUserSummaryByIdResponses = {
    /**
     * OK
     */
    200: UserSummary;
};

export type GetUserSummaryByIdResponse = GetUserSummaryByIdResponses[keyof GetUserSummaryByIdResponses];

export type GetCurrentUserSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/summary/me';
};

export type GetCurrentUserSummaryErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
};

export type GetCurrentUserSummaryError = GetCurrentUserSummaryErrors[keyof GetCurrentUserSummaryErrors];

export type GetCurrentUserSummaryResponses = {
    /**
     * OK
     */
    200: UserSummary;
};

export type GetCurrentUserSummaryResponse = GetCurrentUserSummaryResponses[keyof GetCurrentUserSummaryResponses];

export type GetUserTestResultsData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/api/results/user/{userId}/tests';
};

export type GetUserTestResultsErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
};

export type GetUserTestResultsError = GetUserTestResultsErrors[keyof GetUserTestResultsErrors];

export type GetUserTestResultsResponses = {
    /**
     * OK
     */
    200: TestResultByUser;
};

export type GetUserTestResultsResponse = GetUserTestResultsResponses[keyof GetUserTestResultsResponses];

export type GetUserFormResultsData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/api/results/user/{userId}/forms';
};

export type GetUserFormResultsErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
};

export type GetUserFormResultsError = GetUserFormResultsErrors[keyof GetUserFormResultsErrors];

export type GetUserFormResultsResponses = {
    /**
     * OK
     */
    200: FormAnswersByUser;
};

export type GetUserFormResultsResponse = GetUserFormResultsResponses[keyof GetUserFormResultsResponses];

export type GetUserAllResultsData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/api/results/user/{userId}/all';
};

export type GetUserAllResultsErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
};

export type GetUserAllResultsError = GetUserAllResultsErrors[keyof GetUserAllResultsErrors];

export type GetUserAllResultsResponses = {
    /**
     * OK
     */
    200: ResultsByUser;
};

export type GetUserAllResultsResponse = GetUserAllResultsResponses[keyof GetUserAllResultsResponses];

export type GetAllUsersLatestConfigResultsZipData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/results/user/all/latest/zip';
};

export type GetAllUsersLatestConfigResultsZipErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
};

export type GetAllUsersLatestConfigResultsZipError = GetAllUsersLatestConfigResultsZipErrors[keyof GetAllUsersLatestConfigResultsZipErrors];

export type GetAllUsersLatestConfigResultsZipResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetAllUsersLatestConfigResultsZipResponse = GetAllUsersLatestConfigResultsZipResponses[keyof GetAllUsersLatestConfigResultsZipResponses];

export type GetAllUsersLatestConfigTestsZipData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/results/user/all/latest/tests/zip';
};

export type GetAllUsersLatestConfigTestsZipErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
};

export type GetAllUsersLatestConfigTestsZipError = GetAllUsersLatestConfigTestsZipErrors[keyof GetAllUsersLatestConfigTestsZipErrors];

export type GetAllUsersLatestConfigTestsZipResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetAllUsersLatestConfigTestsZipResponse = GetAllUsersLatestConfigTestsZipResponses[keyof GetAllUsersLatestConfigTestsZipResponses];

export type GetAllUsersLatestConfigFormsZipData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/results/user/all/latest/forms/zip';
};

export type GetAllUsersLatestConfigFormsZipErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
};

export type GetAllUsersLatestConfigFormsZipError = GetAllUsersLatestConfigFormsZipErrors[keyof GetAllUsersLatestConfigFormsZipErrors];

export type GetAllUsersLatestConfigFormsZipResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetAllUsersLatestConfigFormsZipResponse = GetAllUsersLatestConfigFormsZipResponses[keyof GetAllUsersLatestConfigFormsZipResponses];

export type GetGroupTestResultsZipData = {
    body?: never;
    path: {
        groupId: number;
    };
    query?: never;
    url: '/api/results/group/{groupId}/tests';
};

export type GetGroupTestResultsZipErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
};

export type GetGroupTestResultsZipError = GetGroupTestResultsZipErrors[keyof GetGroupTestResultsZipErrors];

export type GetGroupTestResultsZipResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetGroupTestResultsZipResponse = GetGroupTestResultsZipResponses[keyof GetGroupTestResultsZipResponses];

export type GetGroupFormResultsZipData = {
    body?: never;
    path: {
        groupId: number;
    };
    query?: never;
    url: '/api/results/group/{groupId}/forms';
};

export type GetGroupFormResultsZipErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
};

export type GetGroupFormResultsZipError = GetGroupFormResultsZipErrors[keyof GetGroupFormResultsZipErrors];

export type GetGroupFormResultsZipResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetGroupFormResultsZipResponse = GetGroupFormResultsZipResponses[keyof GetGroupFormResultsZipResponses];

export type GetGroupFullResultsZipData = {
    body?: never;
    path: {
        groupId: number;
    };
    query?: never;
    url: '/api/results/group/{groupId}/all';
};

export type GetGroupFullResultsZipErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
};

export type GetGroupFullResultsZipError = GetGroupFullResultsZipErrors[keyof GetGroupFullResultsZipErrors];

export type GetGroupFullResultsZipResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetGroupFullResultsZipResponse = GetGroupFullResultsZipResponses[keyof GetGroupFullResultsZipResponses];

export type GetAllEventLogsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/event-logs';
};

export type GetAllEventLogsErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
};

export type GetAllEventLogsError = GetAllEventLogsErrors[keyof GetAllEventLogsErrors];

export type GetAllEventLogsResponses = {
    /**
     * OK
     */
    200: Array<QuestionEventLogWithUserId>;
};

export type GetAllEventLogsResponse = GetAllEventLogsResponses[keyof GetAllEventLogsResponses];

export type GetUserEventLogsData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/api/event-logs/{userId}';
};

export type GetUserEventLogsErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
};

export type GetUserEventLogsError = GetUserEventLogsErrors[keyof GetUserEventLogsErrors];

export type GetUserEventLogsResponses = {
    /**
     * OK
     */
    200: Array<QuestionEventLog>;
};

export type GetUserEventLogsResponse = GetUserEventLogsResponses[keyof GetUserEventLogsResponses];

export type GetAllConfigsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/configs';
};

export type GetAllConfigsErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
};

export type GetAllConfigsError = GetAllConfigsErrors[keyof GetAllConfigsErrors];

export type GetAllConfigsResponses = {
    /**
     * OK
     */
    200: Array<ConfigPreview>;
};

export type GetAllConfigsResponse = GetAllConfigsResponses[keyof GetAllConfigsResponses];

export type DeleteConfigData = {
    body?: never;
    path: {
        version: number;
    };
    query?: never;
    url: '/api/configs/{version}';
};

export type DeleteConfigErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
};

export type DeleteConfigError = DeleteConfigErrors[keyof DeleteConfigErrors];

export type DeleteConfigResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetConfigByVersionData = {
    body?: never;
    path: {
        version: number;
    };
    query?: never;
    url: '/api/configs/{version}';
};

export type GetConfigByVersionErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
};

export type GetConfigByVersionError = GetConfigByVersionErrors[keyof GetConfigByVersionErrors];

export type GetConfigByVersionResponses = {
    /**
     * OK
     */
    200: FullConfig;
};

export type GetConfigByVersionResponse = GetConfigByVersionResponses[keyof GetConfigByVersionResponses];

export type GetActiveConfigAsAdminData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/configs/active/full';
};

export type GetActiveConfigAsAdminErrors = {
    /**
     * Unauthorized
     */
    401: ApiHttpError;
    /**
     * Forbidden
     */
    403: ApiHttpError;
};

export type GetActiveConfigAsAdminError = GetActiveConfigAsAdminErrors[keyof GetActiveConfigAsAdminErrors];

export type GetActiveConfigAsAdminResponses = {
    /**
     * OK
     */
    200: FullConfig;
};

export type GetActiveConfigAsAdminResponse = GetActiveConfigAsAdminResponses[keyof GetActiveConfigAsAdminResponses];
