// This file is auto-generated by @hey-api/openapi-ts

export type UserSummary = {
  id: string;
  name: string;
  email?: string;
  age?: number;
  group: string;
  timestamp: number;
  timeTaken: number;
  correctQuestions: number;
  questionsAnswered: number;
  accuracy: number;
};

export type Summary = {
  averageAccuracy: number;
  averageTimeTaken: number;
  totalQuestionsAnswered: number;
  users: Array<UserSummary>;
};

export type TimelogEventDto = {
  type: "deselect" | "hover" | "select";
  optionId: number;
  timestamp: number;
};

export type TimelogDto = {
  userId: string;
  phaseId: number;
  questionId: number;
  startTimestamp: number;
  endTimestamp: number;
  correct: boolean;
  skipped: boolean;
  totalOptionChanges: number;
  totalOptionHovers: number;
  events: Array<TimelogEventDto>;
};

export type TimelogEvent = {
  type: "deselect" | "hover" | "select";
  optionId: number;
  timestamp: number;
};

export type Timelog = {
  userId: string;
  phaseId: number;
  questionId: number;
  startTimestamp: number;
  endTimestamp: number;
  correct: boolean;
  skipped: boolean;
  totalOptionChanges: number;
  totalOptionHovers: number;
  events: Array<TimelogEvent>;
};

export type UserDto = {
  anonymous: boolean;
  id: string;
  group: string;
  name?: string;
  email?: string;
  age?: number;
};

export type User = {
  anonymous: boolean;
  id: string;
  group: string;
  name?: string;
  email?: string;
  age?: number;
};

export type GetSummaryData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/dashboard";
};

export type GetSummaryResponses = {
  200: Summary;
};

export type GetSummaryResponse = GetSummaryResponses[keyof GetSummaryResponses];

export type GetAllTimelogsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/timelogs";
};

export type GetAllTimelogsResponses = {
  200: Array<Timelog>;
};

export type GetAllTimelogsResponse = GetAllTimelogsResponses[keyof GetAllTimelogsResponses];

export type SaveTimelogData = {
  body: TimelogDto;
  path?: never;
  query?: never;
  url: "/timelogs";
};

export type SaveTimelogResponses = {
  201: unknown;
};

export type GetUsersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users";
};

export type GetUsersResponses = {
  200: Array<User>;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type SaveUserData = {
  body: UserDto;
  path?: never;
  query?: never;
  url: "/users";
};

export type SaveUserResponses = {
  201: unknown;
};

export type GetUserTimelogsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/users/{id}/timelogs";
};

export type GetUserTimelogsResponses = {
  200: Array<Timelog>;
};

export type GetUserTimelogsResponse = GetUserTimelogsResponses[keyof GetUserTimelogsResponses];

export type PingData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/ping";
};

export type PingResponses = {
  200: unknown;
};

export type ClientOptions = {
  baseURL: `${string}://api` | (string & {});
};
