// This file is auto-generated by @hey-api/openapi-ts

export type FieldErrorResponse = {
    field?: string;
    message?: string;
};

export type MultiFieldException = {
    cause?: {
        stackTrace?: Array<{
            classLoaderName?: string;
            moduleName?: string;
            moduleVersion?: string;
            methodName?: string;
            fileName?: string;
            lineNumber?: number;
            className?: string;
            nativeMethod?: boolean;
        }>;
        message?: string;
        localizedMessage?: string;
    };
    stackTrace?: Array<{
        classLoaderName?: string;
        moduleName?: string;
        moduleVersion?: string;
        methodName?: string;
        fileName?: string;
        lineNumber?: number;
        className?: string;
        nativeMethod?: boolean;
    }>;
    errors?: Array<FieldErrorResponse>;
    message?: string;
    suppressed?: Array<{
        stackTrace?: Array<{
            classLoaderName?: string;
            moduleName?: string;
            moduleVersion?: string;
            methodName?: string;
            fileName?: string;
            lineNumber?: number;
            className?: string;
            nativeMethod?: boolean;
        }>;
        message?: string;
        localizedMessage?: string;
    }>;
    localizedMessage?: string;
};

export type CreateUserRequest = {
    /**
     * Username by user like rut or other identifier
     */
    username: string;
    groupId: number;
    anonymous: boolean;
    name: string;
    email: string;
    age: number;
    password?: string;
};

export type UploadImageResponse = {
    url?: string;
};

export type FormAnswerRequest = {
    userId: number;
    formId: number;
    answers: Array<QuestionAnswer>;
};

export type QuestionAnswer = {
    questionId: number;
    optionId: number;
    value: number;
    answer: string;
};

export type User = {
    id: number;
    username: string;
    name: string;
    anonymous: boolean;
    email: string;
    age: number;
};

export type Event = {
    type: string;
    optionId: number;
    timestamp: number;
};

export type TimeLog = {
    userId: number;
    phaseId: number;
    questionId: number;
    startTimestamp: number;
    endTimestamp: number;
    skipped: boolean;
    correct: boolean;
    totalOptionChanges: number;
    totalOptionHovers: number;
    events: Array<Event>;
};

export type TotalUserSummary = {
    averageAccuracy: number;
    averageTimeTaken: number;
    totalQuestionsAnswered: number;
    users: Array<UserSummary>;
};

export type UserSummary = {
    id: number;
    name: string;
    email: string;
    age: number;
    group: string;
    timestamp: number;
    timeTaken: number;
    correctQuestions: number;
    questionsAnswered: number;
    accuracy: number;
};

export type Faq = {
    question: string;
    answer: string;
};

export type Form = {
    id: number;
    /**
     * Form questions
     */
    questions: Array<SelectMultiple | SelectOne | Slider | TextLong | TextShort>;
};

export type FormOption = {
    id: number;
    text?: string;
    image?: Image;
};

export type FormQuestion = unknown;

export type Group = {
    id: number;
    /**
     * Probability between 0 and 100
     */
    probability: number;
    label: string;
    greeting: string;
    protocol: Protocol;
};

export type Image = {
    url?: string;
    alt?: string;
};

export type InformationCard = {
    title: string;
    description: string;
    color: string;
    icon?: Image;
};

export type Option = {
    id: number;
    text?: string;
    image?: Image;
    correct: boolean;
};

export type Phase = {
    id: number;
    questions: Array<Question>;
};

export type Protocol = {
    allowPreviousPhase: boolean;
    allowPreviousQuestion: boolean;
    allowSkipQuestion: boolean;
    phases: Array<Phase>;
};

export type Question = {
    id: number;
    text?: string;
    image: Image;
    options: Array<Option>;
};

export type SelectMultiple = FormQuestion & {
    id: number;
    category: string;
    text?: string;
    image?: Image;
    type: 'select-one' | 'select-multiple' | 'slider' | 'text-short' | 'text-long';
    options: Array<FormOption>;
    min: number;
    max: number;
    other: boolean;
};

export type SelectOne = FormQuestion & {
    id: number;
    category: string;
    text?: string;
    image?: Image;
    type: 'select-one' | 'select-multiple' | 'slider' | 'text-short' | 'text-long';
    options: Array<FormOption>;
    other: boolean;
};

export type SingleConfigResponse = {
    /**
     * Configuration icon image
     */
    icon?: Image;
    /**
     * Configuration title
     */
    title: string;
    /**
     * Configuration subtitle
     */
    subtitle: string;
    /**
     * Configuration description
     */
    description: string;
    /**
     * Is or not anonymous
     */
    anonymous: boolean;
    /**
     * Card information by configuration
     */
    informationCards: Array<InformationCard>;
    informedConsent: string;
    faq: Array<Faq>;
    preTestForm: Form;
    postTestForm: Form;
    groups: {
        [key: string]: Group;
    };
    translations: {
        [key: string]: string;
    };
};

export type Slider = FormQuestion & {
    id: number;
    category: string;
    text?: string;
    image?: Image;
    type: 'select-one' | 'select-multiple' | 'slider' | 'text-short' | 'text-long';
    placeholder: string;
    min: number;
    max: number;
    step: number;
    labels: Array<SliderLabel>;
};

export type SliderLabel = {
    number: number;
    label: string;
};

export type TextLong = FormQuestion & {
    id: number;
    category: string;
    text?: string;
    image?: Image;
    type: 'select-one' | 'select-multiple' | 'slider' | 'text-short' | 'text-long';
    placeholder: string;
    minLength: number;
    maxLength: number;
};

export type TextShort = FormQuestion & {
    id: number;
    category: string;
    text?: string;
    image?: Image;
    type: 'select-one' | 'select-multiple' | 'slider' | 'text-short' | 'text-long';
    placeholder: string;
    minLength: number;
    maxLength: number;
};

export type CreateUserData = {
    body: CreateUserRequest;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type CreateUserErrors = {
    /**
     * Validation error
     */
    400: MultiFieldException;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * User created successfully
     */
    200: string;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type UploadImageData = {
    body?: never;
    path?: never;
    query: {
        file: Blob | File;
        path: string;
    };
    url: '/api/images';
};

export type UploadImageResponses = {
    /**
     * OK
     */
    200: UploadImageResponse;
};

export type UploadImageResponse2 = UploadImageResponses[keyof UploadImageResponses];

export type SubmitFormAnswersData = {
    body: FormAnswerRequest;
    path?: never;
    query?: never;
    url: '/api/forms/answer';
};

export type SubmitFormAnswersResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type SubmitFormAnswersResponse = SubmitFormAnswersResponses[keyof SubmitFormAnswersResponses];

export type GetUserData = {
    body?: never;
    path: {
        username: string;
    };
    query?: never;
    url: '/api/users/{username}';
};

export type GetUserResponses = {
    /**
     * OK
     */
    200: User;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type GetAllUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/all';
};

export type GetAllUsersResponses = {
    /**
     * OK
     */
    200: Array<User>;
};

export type GetAllUsersResponse = GetAllUsersResponses[keyof GetAllUsersResponses];

export type GetAllTimeLogsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/timelogs';
};

export type GetAllTimeLogsResponses = {
    /**
     * OK
     */
    200: Array<TimeLog>;
};

export type GetAllTimeLogsResponse = GetAllTimeLogsResponses[keyof GetAllTimeLogsResponses];

export type GetUserTimelogsData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/api/timelogs/{userId}';
};

export type GetUserTimelogsResponses = {
    /**
     * OK
     */
    200: TimeLog;
};

export type GetUserTimelogsResponse = GetUserTimelogsResponses[keyof GetUserTimelogsResponses];

export type GetAllUserSummariesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/summary';
};

export type GetAllUserSummariesResponses = {
    /**
     * OK
     */
    200: TotalUserSummary;
};

export type GetAllUserSummariesResponse = GetAllUserSummariesResponses[keyof GetAllUserSummariesResponses];

export type GetUserSummaryByIdData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/api/summary/{userId}';
};

export type GetUserSummaryByIdResponses = {
    /**
     * OK
     */
    200: UserSummary;
};

export type GetUserSummaryByIdResponse = GetUserSummaryByIdResponses[keyof GetUserSummaryByIdResponses];

export type GetLastestConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/config/latest';
};

export type GetLastestConfigResponses = {
    /**
     * OK
     */
    200: SingleConfigResponse;
};

export type GetLastestConfigResponse = GetLastestConfigResponses[keyof GetLastestConfigResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};